### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by arxivi** [LnVault/lnvault-plugin#1]
Hello! Please update to new versions of EssentialsX and Minecraft (1.19.3-1.19.4).

For example, in the output of the balance is not fixed change in the game after updates to dependent plugins. And in general. Is everything all right with you? :(

Thanks!

**Comment by arxivi** [comment]
Glad to hear you're still okay.

Yes, I am creating an anarcho-capitalist server. You created the most perfect plugin to simulate the economy in game mechanics. 

It worked for me, but after I did a full build - it stopped fixing the withdrawal in game balance (in real is ok). Also the payment success status doesn't work and I can't understand the overall timeout for balance withdrawal.

Generally you are right. Minecrafters are crazy interested in this. Just from experience positioning it only for Bitcoin community is a very flawed hypothesis (I check it). 

Thanks to your plugin,my users was introduced to Lightning Network and Bitcoin. I see it as an element of educating and teaching teens and their parents about the basics of a free economy.

How can I contact you more substantively? Maybe there is a contact for you?

p.s. I can give you full access to the host or settings.

**Comment by LnVault** [comment]
I've tested with 

- paper-1.19.4-468.jar
- Vault.jar 1.7.3
- EssentialsX-2.20.0-dev+45-bf14b88.jar

I was able to both /lndeposit and /lnwithdraw and /balance updated correctly on both cases.

I did have an issue with /lnwithdraw the OpenNode API key is bound to an IP Address. Since I last tested my IP address has changed and I had to generate a new Withdrawal API Key and update it using /lnconfig set opennode.withdraw.key

Hopefully its a similar config issue for you?

**Comment by LnVault** [comment]
We can chat on Discord if that helps. I created an LnVault server here https://discord.gg/v3hKtzDFZj

**Comment by arxivi** [comment]
> I've tested with
> 
> * paper-1.19.4-468.jar
> * Vault.jar 1.7.3
> * EssentialsX-2.20.0-dev+45-bf14b88.jar
> 
> I was able to both /lndeposit and /lnwithdraw and /balance updated correctly on both cases.
> 
> I did have an issue with /lnwithdraw the OpenNode API key is bound to an IP Address. Since I last tested my IP address has changed and I had to generate a new Withdrawal API Key and update it using /lnconfig set opennode.withdraw.key
> 
> Hopefully its a similar config issue for you?

Yes, I set it up correctly.

My plugins: AdvancedEnchantments, AdvancedTeleport, BetterFarming, ChestCleaner, ChestProtect, ChestSort, Chunky, Citizens, ClansLite, ClearLag, ClearLagTimer, Contracts, CoreProtect, CrazyAuctions, CustomMaps, dtlTradersPlus, DynamicLights, EconomyShopGUI-Premium, Essentials, EssentialsChat, EssentialsSpawn, EzChat, ImageMapRenderer, ItemJoin, ItemsAdder, Lands, LightAPI, LnVault, LoginSecurity*, LoneLibs, LuckPerms, MapMenu, MOTD, PL-Hide, PlaceholderAPI, ProtocolLib, RandomTP, RealisticSeasons, ServerListPlus*, SkinsRestorer, Stonks, TAB, TimeIsMoney, TradeSystem, UpgradeableHoppers, UpgradeableSpawners, Vault, WorldEdit

Vault 1.7.3-b131
EssentialsX X-2.20.0-dev+45-bf14b88.jar
Paper 1.19.4
Java 18

Perhaps something conflicts? From all the changes in your file, I only used my logo and server name (short) in the transaction at output. Here is the ip of the server: liberty.mcmagic.space Java. 1.19.3

The balance output itself is done, but the game does not show the balance changes and the status of the successful balance output. 

I wrote to the server in Discord.

**Comment by arxivi** [comment]
Perhaps the option to recreate the assembly? But it would not be desirable :(

**Comment by LnVault** [comment]
As discussed on Discord. I've added new configuration options

/lnconfig set deposit.description Deposit ${0}
/lnconfig set withdrawal.description Withdrawal ${0} - {1}

You can replace the text with your own message

{0} will be replaced by the amount and for withdrawals the {1} will be replaced by the id.
For withdrawals the description MUST contain a {1} in order for withdrawals to be confirmed.

I modified withdrawals to immediately deduct from the users balance. If users fail to withdraw you will have to give them their in game balance back manually. This should stop users from being able to withdraw more than their balance.

I improved the error handling a little and it is now possible to create a new withdrawal even if the current one is still pending.

The new binary is available here https://lnvault.github.io/binaries/lnvault-1.1-SNAPSHOT.jar

I need to do some more research on how I can get reliable withdrawal confirmations working with a callback from OpenNode.
